name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  main:
    strategy:
      fail-fast: false 
      matrix:
        OS: ['ubuntu', 'macos', 'windows']
        PYTHON_VERSION: ['3.9', '3.10', '3.11']
        SPYDER_SOURCE: ['conda', 'git']
    name: ${{ matrix.OS }} py${{ matrix.PYTHON_VERSION }} spyder-from-${{ matrix.SPYDER_SOURCE }}
    runs-on: ${{ matrix.OS }}-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
           path: 'spyder-unittest'
      - name: Install System Packages
        if: matrix.OS == 'ubuntu'
        run: | 
          sudo apt-get update --fix-missing
          sudo apt-get install -qq pyqt5-dev-tools libxcb-xinerama0 xterm --fix-missing
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
           miniforge-version: latest
           auto-update-conda: true
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Checkout Spyder from git
        if: matrix.SPYDER_SOURCE == 'git'
        uses: actions/checkout@v4
        with:
          repository: 'spyder-ide/spyder'
          path: 'spyder'
      - name: Install Spyder's dependencies (main)
        if: matrix.SPYDER_SOURCE == 'git'
        shell: bash -l {0}
        run: mamba env update --file spyder/requirements/main.yml
      - name: Install Spyder's dependencies (Linux)
        if: matrix.SPYDER_SOURCE == 'git' && matrix.OS == 'ubuntu'
        shell: bash -l {0}
        run: mamba env update --file spyder/requirements/linux.yml
      - name: Install Spyder's dependencies (Mac / Windows)
        if: matrix.SPYDER_SOURCE == 'git' && matrix.OS != 'ubuntu'
        shell: bash -l {0}
        run: mamba env update --file spyder/requirements/${{ matrix.OS }}.yml
      - name: Install Spyder from source
        if: matrix.SPYDER_SOURCE == 'git'
        shell: bash -l {0}
        run: pip install --no-deps spyder
      - name: Install plugin dependencies (without Spyder)
        if: matrix.SPYDER_SOURCE == 'git'
        shell: bash -l {0}
        run: |
          python spyder-unittest/.github/scripts/generate-without-spyder.py
          mamba install --file spyder-unittest/requirements/without-spyder.txt -y
      - name: Install plugin dependencies
        if: matrix.SPYDER_SOURCE == 'conda'
        shell: bash -l {0}
        run: mamba install --file spyder-unittest/requirements/conda.txt -y
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          mamba install nomkl -y -q
          mamba install --file spyder-unittest/requirements/tests.txt -y
      - name: Install plugin
        shell: bash -l {0}
        run: pip install --no-deps spyder-unittest
      - name: Show environment information
        shell: bash -l {0}
        run: |
          mamba info
          mamba list
      - name: Run tests (Linux)
        if: matrix.OS == 'ubuntu'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          shell: bash
          command: |
            . ~/.profile
            xvfb-run --auto-servernum pytest spyder-unittest/spyder_unittest -vv
      - name: Run tests (MacOS)
        if: matrix.OS == 'macos'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          shell: bash
          command: |
            . ~/.profile
            pytest spyder-unittest/spyder_unittest -vv
      - name: Run tests (Windows)
        if: matrix.OS == 'windows'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pytest spyder-unittest/spyder_unittest -vv
